### ISSUE TITLE
Docker: unauthorized

### ISSUE THREAD

**Issue by 0x8b** [collabora/WhisperFusion#12]
After running `sudo docker run --gpus all --shm-size 64G -p 6006:6006 -p 8888:8888 -it ghcr.io/collabora/whisperfusion:latest` I got:

```sh
Unable to find image 'ghcr.io/collabora/whisperfusion:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/collabora/whisperfusion/manifests/latest": unauthorized.
See 'docker run --help'.
```

**Comment by thunder95** [comment]
same problem

**Comment by zoq** [comment]
Thanks for opening the issue, fixed, you should be able to pull the image now.

**Comment by smcalilly** [comment]
I get a denied error after trying the command in the readme:
```
docker run --gpus all --shm-size 64G -p 6006:6006 -p 8888:8888 -it ghcr.io/collabora/whisperfusion:latest
Unable to find image 'ghcr.io/collabora/whisperfusion:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/collabora/whisperfusion/manifests/latest": denied: denied.
See 'docker run --help'.
```

**Comment by zoq** [comment]
I just did a fresh `docker pull ghcr.io/collabora/whisperfusion:latest` and it download the container on my end. And I can also see, downloads on the container itself. Can you check with the `docker pull` command again?

**Comment by smcalilly** [comment]
@zoq same problem:
```
docker pull ghcr.io/collabora/whisperfusion:latest
Error response from daemon: Head "https://ghcr.io/v2/collabora/whisperfusion/manifests/latest": denied: denied
```

**Comment by makaveli10** [comment]
@smcalilly could you try after logging out of `ghcr.io`?
```
docker logout ghcr.io
docker pull ghcr.io/collabora/whisperfusion:latest
```

I suspect your PAT has expired but since this image is public you should be able to pull without any authentication.

**Comment by smcalilly** [comment]
@makaveli10 yep that was it. Thanks for the tip!

**Comment by makaveli10** [comment]
@0x8b @thunder95 Did you guys manage to pull the image?
