### ISSUE TITLE
WhisperLive `segments` only transcribe last 25 seconds

### ISSUE THREAD

**Issue by DamianB-BitFlipper** [collabora/WhisperFusion#26]
Code reference: https://github.com/collabora/WhisperFusion/blob/main/whisper_live/trt_server.py#L376-L389

The highlighted code does not make logical sense to me and seems buggy. Mostly that `segments` is only the `last_segment`. The `last_segment` is the clipped audio of the last 25 seconds. If someone talks for longer than 25 seconds with no EOS in between, then the demo UI would not record the earliest part of the conversation. Also the point of line 380 makes no clear sense.

I am trying to understand how this works with the UI. Looking at the `server.py` code of the most recent `WhisperLive` makes much more sense.

**Comment by makaveli10** [comment]
Yes, segments is only the last_segment. We have to clean this up but it was good to start with. And yes, you're right about the last 25 seconds as well. Currently, we support short exchanges, we will support interruptions and long exchanges in the conversation in upcoming updates. Thanks for your interest in the project.

**Comment by DamianB-BitFlipper** [comment]
Ok!
