### ISSUE TITLE
expected 8.0 but got 8.9

### ISSUE THREAD

**Issue by LEAGUEDORA** [collabora/WhisperFusion#39]
Hello, when I am running the `docker run --gpus all --shm-size 64G -p 6006:6006 -p 8888:8888 -it ghcr.io/collabora/whisperfusion:latest` I got the following error `expected compute 8.0 but got compute 8.9`. I am trying to run this on A100 80GB GPU in GCP. I have read the docs and it said to run like this to build for a new arch `bash build.sh 86-real`. Now should I build like 

```sh
bash build.sh 8.9-real
```

or

```sh
bash build.sh 89-real
```

**Comment by makaveli10** [comment]
Hello @LEAGUEDORA, the compute capability of A100 is `8.0` so, the command that you should use to build would come down to:
```
bash build.sh 80-real
```

Let us know, if you run into issues.
