### ISSUE TITLE
sometimes no response or not stable

### ISSUE THREAD

**Issue by twmht** [collabora/WhisperFusion#49]
![image](https://github.com/collabora/WhisperFusion/assets/1567200/9115261d-a29e-4e09-8109-9403de09305d)

sometimes it does not have response and sometimes no text-to-speech generated. why?

**Comment by makaveli10** [comment]
@twmht we made Phi-3 our default model, just follow the readme and try it and see if it fixes your issue with stability
https://github.com/collabora/WhisperFusion/pull/53
