### ISSUE TITLE
error run docker compose - python3: command not found in build-trt-llm.sh

### ISSUE THREAD

**Issue by davideuler** [collabora/WhisperFusion#50]
ARG BASE_IMAGE=nvcr.io/nvidia/cuda
 => [whisperfusion internal] load .dockerignore                                                                 0.0s
 => => transferring context: 2B                                                                                 0.0s
 => [whisperfusion internal] load build definition from Dockerfile                                              0.0s
 => => transferring dockerfile: 805B                                                                            0.0s
 => [whisperfusion internal] load metadata for nvcr.io/nvidia/cuda:12.2.2-devel-ubuntu22.04                     0.0s
 => [whisperfusion base 1/2] FROM nvcr.io/nvidia/cuda:12.2.2-devel-ubuntu22.04                                  0.0s
 => [whisperfusion internal] load build context                                                                 0.0s
 => => transferring context: 212B                                                                               0.0s
 => CACHED [whisperfusion base 2/2] RUN apt-get update &&     apt-get install -y --no-install-recommends     x  0.0s
 => CACHED [whisperfusion devel 1/5] WORKDIR /root                                                              0.0s
 => CACHED [whisperfusion devel 2/5] COPY scripts/install-deps.sh /root                                         0.0s
 => CACHED [whisperfusion devel 3/5] RUN bash install-deps.sh && rm install-deps.sh                             0.0s
 => CACHED [whisperfusion devel 4/5] COPY scripts/build-trt-llm.sh /root                                        0.0s
 => ERROR [whisperfusion devel 5/5] RUN bash build-trt-llm.sh && rm build-trt-llm.sh                            0.3s
------
 > [whisperfusion devel 5/5] RUN bash build-trt-llm.sh && rm build-trt-llm.sh:
0.244 build-trt-llm.sh: line 9: python3: command not found

**Comment by makaveli10** [comment]
Closed by #52
