### ISSUE TITLE
Issue building on windows

### ISSUE THREAD

**Issue by sadimoodi** [collabora/WhisperFusion#51]
hello,
I am trying to run the docker on my windows 11 with RTX 4090, i used the following command (no image for 4090)
`docker run --gpus all --shm-size 64G -p 6006:6006 -p 8888:8888 -it ghcr.io/collabora/whisperfusion-3090:latest`
but it failed with this error:
![image](https://github.com/collabora/WhisperFusion/assets/32739021/cb75a041-6f3a-4042-872a-88af88e0a69e)

**Comment by sadimoodi** [comment]
@makaveli10  can u help? i changed the following but still getting the same error
ARG CUDA_ARCH='89-real'
ENV CUDA_ARCH='89-real'

**Comment by makaveli10** [comment]
@sadimoodi thanks for using WhisperFusion, we have been a bit busy with other projects. Windows hasnt been in our test environment. That being said, we will test the setup on windows and get back to you.

**Comment by sadimoodi** [comment]
@makaveli10 thanks, will wait eagerly

**Comment by makaveli10** [comment]
@sadimoodi can you test https://github.com/collabora/WhisperFusion/pull/53 if it resolves your issue.
