### ISSUE TITLE
Whisper Live ONNX Runtime Error

### ISSUE THREAD

**Issue by rahulanand2** [collabora/WhisperFusion#54]
VAD model gives the below error on start of transcription.
INVALID_PROTOBUF : Load model from /root/.cache/whisper-live/silero_vad.onnx failed:Protobuf parsing failed.

**Comment by Alima88** [comment]
see this:
https://github.com/livekit/agents/issues/420

**Comment by Alima88** [comment]
I used this method and it solved temporarily:

```bash
docker compose up -d --build
docker compose exec whisperfusion bash
```
and 
``` bash
cd .cache/whisper-live/
rm silero_vad.onnx
wget https://github.com/snakers4/silero-vad/raw/v4.0/files/silero_vad.onnx
```

Then exit the terminal and the system works properly

**Comment by Alima88** [comment]
You can simply edit this file:

docker/scripts/setup-whisperfusion.sh:22 to

```
curl -L -o /root/.cache/whisper-live/silero_vad.onnx https://github.com/snakers4/silero-vad/raw/v4.0/files/silero_vad.onnx
```
