### ISSUE TITLE
Phi-3-mini-128k-instruct tokenizer missing

### ISSUE THREAD

**Issue by Kkkassini** [collabora/WhisperFusion#55]
export MODEL=Phi-3-mini-128k-instruct 
docker compose up returns 
` Process Process-3:
whisperfusion-1  | Traceback (most recent call last):
whisperfusion-1  |   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
whisperfusion-1  |     self.run()
whisperfusion-1  |   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
whisperfusion-1  |     self._target(*self._args, **self._kwargs)
whisperfusion-1  |   File "/root/WhisperFusion/llm_service.py", line 223, in run
whisperfusion-1  |     self.initialize_model(
whisperfusion-1  |   File "/root/WhisperFusion/llm_service.py", line 110, in initialize_model
whisperfusion-1  |     self.tokenizer, self.pad_id, self.end_id = load_tokenizer(
whisperfusion-1  |   File "/root/WhisperFusion/llm_service.py", line 58, in load_tokenizer
whisperfusion-1  |     tokenizer = AutoTokenizer.from_pretrained(tokenizer_dir,
whisperfusion-1  |   File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/tokenization_auto.py", line 819, in from_pretrained
whisperfusion-1  |     config = AutoConfig.from_pretrained(
whisperfusion-1  |   File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 928, in from_pretrained
whisperfusion-1  |     config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
whisperfusion-1  |   File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 631, in get_config_dict
whisperfusion-1  |     config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
whisperfusion-1  |   File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 686, in _get_config_dict
whisperfusion-1  |     resolved_config_file = cached_file(
whisperfusion-1  |   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 369, in cached_file
whisperfusion-1  |     raise EnvironmentError(
whisperfusion-1  | OSError: /root/scratch-space/models/Phi-3-mini-128k-instruct/tokenizer does not appear to have a file named config.json. Checkout 'https://huggingface.co//root/scratch-space/models/Phi-3-mini-128k-instruct/tokenizer/tree/None' for available files.
whisperfusion-1  | /usr/local/lib/python3.10/dist-packages/torch/nn/utils/weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
whisperfusion-1  |   warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
whisperfusion-1  | INFO:root:`

**Comment by Kkkassini** [comment]
phi-2 returns 
`cp: failed to access 'added_tokens.json/root/scratch-space/models/phi-2/tokenizer': Not a directory`

**Comment by makaveli10** [comment]
@Kkkassini feel free to test out the PR and let us know if the issue is fixed.
